name: Run KOSPI Breakout Detector

on:
  schedule:
    - cron: '30 7 * * *'     # 매일 KST 16:30
  workflow_dispatch:

jobs:
  breakout-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # ────────────────────────────────
      # ① 서비스 계정 키 파일 복원
      # ────────────────────────────────
      # • 리포지토리 Secrets → GSHEET_KEY (= JSON 전체를 base64 인코딩) 을 미리 등록
      # • sheet_logger.py 가 gsheet_key.json 을 찾도록 루트에 저장
      - name: ■ Write gsheet_key.json
        run:  |-
          echo "$GSHEET_KEY" | base64 -d > gsheet_key.json
        env:
          GSHEET_KEY: ${{ secrets.GSHEET_KEY }}

      # ────────────────────────────────
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"   # 원래 3.9 사용 중이면 그대로 3.9 도 OK

      # ────────────────────────────────
      # ② 의존성 설치 (gspread · google-auth 추가)
      # ────────────────────────────────
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pykrx requests gspread google-auth

      # ────────────────────────────────
      - name: Run breakout detector
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python detector.py
