name: Run KOSPI Breakout Detector

on:
  schedule:
    - cron: '30 5 * * *'  # 한국시간 14:30 (UTC 기준 05:30)
  workflow_dispatch:

jobs:
  breakout-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pykrx requests

      - name: Run breakout detector
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python detector.py